Memory leak in intvector classes fixed
LLNL/hiop pull request #154
Opened 2020-12-11 19:42 UTC by ashermancinelli

I found this bug reviewing the impl since according to @pelesh we'll be using these in the near future.

2020-12-18 20:03 UTC, ashermancinelli commented
@pelesh Can you take a quick look at this?

2021-05-12 02:51 UTC, pelesh requested changes
I believe logic for allocating RAJA vector needs to be updated per my earlier comment. Also see [hiopVectorRajaPar](https://github.com/LLNL/hiop/blob/develop/src/LinAlg/hiopVectorRajaPar.cpp#L140) class implementation.

2021-05-12 17:14 UTC, ashermancinelli commented on src/LinAlg/hiopVectorIntRaja.cpp
> +  buf_dev_ = nullptr;
This is a good point - thanks for the review!

2021-05-12 20:45 UTC, ashermancinelli commented on src/LinAlg/hiopVectorIntRaja.cpp
> +  buf_dev_ = nullptr;
I believe this should be resolved in 4203d6d.

2021-05-12 20:45 UTC, ashermancinelli commented
Rebased on recent develop. I also ran into a bug with our Valgrind tests in CMake, so there is a fix for that too.

2021-05-13 23:09 UTC, pelesh approved these changes
Looks good! I think we can merge.

2021-05-14 03:30 UTC, merged