Magma device inertia
LLNL/hiop pull request #156
Opened 2020-12-14 19:17 UTC by cnpetra

Addresses robustness performance aspects related to using MAGMA on device

* inertia calculation vs dsidi with Bunch-Kaufman solver
* inertia calculation on device with nopiv solver

Requires MAGMA 2.5.4 (uses API introduced in this version)

2020-12-16 16:21 UTC, ashermancinelli approved these changes
I'll try to get this running with the newly installed magma ver on ascent. Also I think this may need a rebase before merging.

2020-12-22 03:02 UTC, pelesh requested changes
This looks good. Perhaps we should make sure Magma 2.5.4 is installed on all CI pipelines before merging this?

2020-12-22 04:38 UTC, ashermancinelli commented on BUILD.sh
> +    module load magma-2.5.4-gcc-7.4.0-vjotnd3 #magma/2.5.3-cuda11
We have it on all but marianas, I'm working on it now.

2020-12-22 21:25 UTC, ashermancinelli commented
I've added magma 2.5.4 builds to all target clusters, and after #169 is merged and this PR is rebased on develop I think it's ready. CC @pelesh

2020-12-23 00:22 UTC, pelesh requested changes
Once #169 is merged, this will be ready to merge, as well.

2020-12-23 22:33 UTC, ashermancinelli commented
> Once #169 is merged, this will be ready to merge, as well.
> 
> CC @cnpetra

Does this need rebase?

2020-12-24 06:19 UTC, pelesh approved these changes
Ready to merge!

2021-01-21 00:17 UTC, merged