CUDA as a first class language + execution policy update
LLNL/hiop pull request #228
Opened 2021-05-10 02:59 UTC by CameronRutherford

Since we have adopted CMake 3.18: as a requirement for this project (see HiOp's spack package [here](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hiop/package.py#L55)), we should adopt CUDA as a first class language per [best practices](https://cliutils.gitlab.io/modern-cmake/chapters/packages/CUDA.html).

Since there still seem to be issues with RAJA and openmp, currently it is advisable to compile RAJA without OpenMP:
- There are a few issues on the RAJA GitHub about this ([example](https://github.com/LLNL/RAJA/issues/1005))
- When compiling RAJA with openmp, errors arise saying openmp is incompatible with current compiler

As a result I removed use of openmp execution policy where it is hard-coded, substituting a sequential policy. Perhaps we should have an option to disable openmp, but this can be done in another MR. This passed all tests when running locally.

cc @pelesh

2021-05-10 05:06 UTC, pelesh commented
I believe we need a little more discussion before this branch is ready to merge. In the meantime, it would be good to create issues that this PR is supposed to address.

2021-05-14 14:53 UTC, ashermancinelli requested changes

2021-05-14 14:53 UTC, ashermancinelli commented on CMakeLists.txt
> +  LANGUAGES C CXX CUDA)
Looks like this pr has been reopened and the cuda language should be removed here.

2021-05-14 14:53 UTC, ashermancinelli commented on src/Drivers/nlpMDS_raja_ex4.cpp
> +    RAJA_LAMBDA(RAJA::Index_type i)
I don't believe this should be addressed here

2021-05-14 16:59 UTC, CameronRutherford commented
@ashermancinelli @pelesh I have resolved all remaining threads. I haven't touched HiOp CI as frequently recently and so I might need some help making sure everything is in order (such as bumping CMake version where necessary).

2021-05-14 23:39 UTC, ashermancinelli commented
Could you update newell CI to load cmake 3.18 module? CI is failing there.

2021-05-17 21:59 UTC, CameronRutherford commented
@ashermancinelli I updated the CMake version on Newell. Assuming CI is passing, I assume this is good to go!

2021-05-19 04:46 UTC, pelesh approved these changes

2021-05-19 04:53 UTC, pelesh commented
I updated description of the PR as it is now more focused.

2021-05-21 23:46 UTC, ashermancinelli approved these changes

2021-05-22 03:54 UTC, pelesh commented
@CameronRutherford, why is CI pipeline skipped for this branch?

2021-05-24 01:18 UTC, ashermancinelli reviewed
Yes, looks like this is passing on ornl but is skipped at pnnl. @CameronRutherford could you look into this?

2021-05-25 01:06 UTC, CameronRutherford commented
@ashermancinelli I understand why CI is failing for this branch (I misconfigured my upstreams, and so the branch history if unverifiable == no CI running). Since these changes are relatively small, and fall within the scope of exporting targets, I am going to just add these changes to #236. There were going to be merge conflicts with these changes anyway, so I think this is the best solution.

cc @pelesh

2021-05-25 01:06 UTC, closed without merging

2021-05-25 01:07 UTC, CameronRutherford commented on cmake/FindHiopCudaLibraries.cmake
> +target_link_libraries(hiop_cuda INTERFACE culibos)
I'll take care of this in #236