Intvec refactor
LLNL/hiop pull request #258
Opened 2021-06-11 15:28 UTC by ashermancinelli

This has been rebased on develop and should address issues surrounding intvector. The data sync methods are now part of the abstract interface and the tests have been updated.

2021-06-11 22:23 UTC, nychiang commented
LGTM! Cheers!

2021-06-11 22:23 UTC, nychiang approved these changes

2021-06-11 22:56 UTC, cnpetra requested changes

2021-06-12 15:59 UTC, ashermancinelli commented
@cnpetra Thanks for the review! I've hopefully addressed your comments.

2021-06-14 16:12 UTC, merged