Add inertia-free approach
LLNL/hiop pull request #315
Opened 2021-09-04 00:39 UTC by nychiang

Add inertia-free approach to HiOp.
Only the dWd curvature test is implemented.

Add one test problem `nlpSparse_Ex7_2` to test inertia-free approach.

@pelesh @cnpetra

2021-09-07 21:18 UTC, cnpetra commented on src/Drivers/nlpSparse_ex7_driver.cpp
> +  if(inertia_free) {
we need to discuss this next time we meet.

2021-09-07 21:19 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysDense.hpp
> +  virtual bool build_kkt_matrix( const double& delta_wx, const double& delta_wd,
alignment

2021-09-07 21:19 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysMDS.cpp
>    {
alignment

2021-09-10 05:24 UTC, nychiang commented
@cnpetra I have addressed all the issues.

2021-09-13 19:14 UTC, cnpetra commented
is this ready for review?

2021-09-13 20:26 UTC, nychiang commented
yes

2021-09-14 16:33 UTC, cnpetra requested changes
looks great, just left a couple of small observations

2021-09-14 16:33 UTC, cnpetra commented on src/Drivers/nlpSparse_ex7.cpp
> + *  min   (2*convex_obj-1)*scal*sum 1/4* { (x_{i}-1)^4 : i=1,...,n} + 0.5x^Tx
please document `scal`. Also not sure the variable name `scal_neg_obj` used later on is the best one. Looks like a better name would be `scale_quartic_obj_term` ...

2021-09-14 16:33 UTC, cnpetra commented on src/Optimization/hiopFactAcceptor.cpp
> +// Please also read �Additional BSD Notice� below.
there are some strange characters enclosing "Additional BSD Notice", please use enclosing quotes

2021-09-14 16:33 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysSparse.cpp
> +  bool hiopKKTLinSysSparseFull::build_kkt_matrix(const double& delta_wx, const double& delta_wd,
alignment

2021-09-14 16:33 UTC, cnpetra commented on src/Utils/hiopOptions.cpp
> +                        "This is the scaling factor which used to determines if the "
remove "which"

2021-09-20 15:53 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysMDS.hpp
this does not seem to be fixed: fix alignment and codestyle

2021-09-20 15:53 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysSparse.cpp
> +  bool hiopKKTLinSysCompressedSparseXYcYd::build_kkt_matrix(const double& delta_wx, const double& delta_wd,
this does not seem to be fixed: fix alignment and codestyle

2021-09-20 15:54 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysSparse.cpp
> +  bool hiopKKTLinSysCompressedSparseXDYcYd::build_kkt_matrix(const double& delta_wx, const double& delta_wd,
this does not seem to be fixed: fix alignment and codestyle

2021-09-20 15:54 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysSparse.cpp
> +  bool hiopKKTLinSysSparseFull::build_kkt_matrix(const double& delta_wx, const double& delta_wd,
this does not seem to be fixed: fix alignment and codestyle

2021-09-20 15:54 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysSparse.hpp
>                              const double& delta_cc, const double& delta_cd);
this does not seem to be fixed: fix alignment and codestyle

2021-09-20 15:55 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysSparse.hpp
>                              const double& delta_cc, const double& delta_cd);
this does not seem to be fixed: fix alignment and codestyle

2021-09-20 15:55 UTC, cnpetra commented on src/Optimization/hiopKKTLinSysSparse.hpp
>                              const double& delta_cc, const double& delta_cd);
this does not seem to be fixed: fix alignment and codestyle

2021-09-20 15:55 UTC, cnpetra commented on src/Utils/hiopOptions.cpp
> +                        "This is the scaling factor which used to determines if the "
not removed

2021-09-20 15:56 UTC, cnpetra commented on src/Optimization/hiopFactAcceptor.cpp
> +// Please also read �Additional BSD Notice� below.
not fixed

2021-09-20 17:59 UTC, cnpetra approved these changes
apparently github does not show the mods correctly. I checked manually and all the issues appear fixed.

2021-09-20 17:59 UTC, merged