Upgrade to RAJA v0.14 and use RAJA::inclusive_scan in HiOp
LLNL/hiop pull request #347
Opened 2021-10-21 22:35 UTC by nychiang

Upgrade to RAJA v0.14 and use RAJA::inclusive_scan in HiOp

NOTE that this PR must be applied AFTER #322  and #333 

CLOSE #342

2022-03-21 23:59 UTC, nychiang commented
@ashermancinelli @cnpetra @pelesh 
I rebased this branch to the latest `develop`, and it passed all the CI tests.
Since now we are using RAJA v0.14, I think this PR is ready.

2022-03-22 21:09 UTC, cnpetra approved these changes

2022-03-22 21:09 UTC, cnpetra commented on src/LinAlg/hiopMatrixRajaSparseTriplet.cpp
> +#if 1 // implemenation that requires a RAJA new version released in Nov.2021
fix "implemenation" typo (multiple occurrences)

2022-03-23 16:36 UTC, ashermancinelli requested changes
I would really like either the cpu version removed, or some way to toggle whether the inclusive scan version is used.

2022-03-23 16:36 UTC, ashermancinelli commented on src/LinAlg/hiopMatrixRajaSparseTriplet.cpp
> +#define RAJA_LAMBDA [=] __device__
I don't see this execution policy used anywhere in this PR, so I'm a bit confused about why it's here. The block size, exec policy, and the `RAJA_LAMBDA` macro should already be defined elsewhere (`hiop_raja_defs.hpp`?).

2022-03-23 16:36 UTC, ashermancinelli commented on src/LinAlg/hiopMatrixRajaSparseTriplet.cpp
> +#if 0 // cpu code due to the RAJA::scan bug
We can always look in the git history to find the cpu implementation if we need it, I recommend we remove this ifdef-ed block.

2022-03-23 16:36 UTC, ashermancinelli commented on src/LinAlg/hiopMatrixRajaSparseTriplet.cpp
> +#if 1 // implemenation that requires a RAJA new version released in Nov.2021
Same comment about this being `ifdef`ed out. If the impls are equivilant and we would like to keep both around, I would prefer to have a macro at the top of this source file to control the behavior, something like `HIOP_MATRIX_RAJA_SP_TRIPLET_USE_RAJA_INCLUSIVE_SCAN` (naming is hard).

2022-03-24 04:20 UTC, nychiang commented
@asher After discussed with Cosmin, I deleted the CPU implementations and added some comments about the latest CPU implementation.

2022-04-13 23:03 UTC, cnpetra commented
I guess this is ready for merging?

2022-04-14 00:02 UTC, nychiang commented
> I guess this is ready for merging?

I thought this had been merged. Let me rebase this PR to the latest develop branch and make sure there is no conflicts.

2022-04-14 00:29 UTC, nychiang commented
> I thought this had been merged. Let me rebase this PR to the latest develop branch and make sure there is no conflicts.

Just confirmed that this branch is safe to be merged into the latest `develop`

2022-04-14 15:47 UTC, cnpetra approved these changes

2022-04-14 15:48 UTC, merged